export const CHALLENGE_DATA = {
  'seven-day': {
    title: '7-Day Vegan Challenge',
    desc: 'Perfect for beginners. Commit to eating fully plant-based for one week and feel the transformation in your energy and mood.',
    badge: 'Earth Champion',
    streak: 7,
    color: 'var(--color-sage)',
    tasks: [
      'Day 1: Blend a fruit & hemp seed smoothie',
      'Day 2: Swap milk for fortified soy or almond milk',
      'Day 3: Prepare a black bean & sweet potato bowl',
      'Day 4: Order a plant-based option at the campus diner',
      'Day 5: Cook the slow-simmered creamy lentil curry',
      'Day 6: Check out our Nutrition Guide B12 facts',
      'Day 7: Pre-prep three healthy plant-based snacks',
    ],
  },
  meatless: {
    title: 'Meatless Mondays',
    desc: 'Small steps, massive footprint impact. Replace meat on your plate every single Monday for three consecutive weeks.',
    badge: 'Green Catalyst',
    streak: 3,
    color: 'var(--color-orange)',
    tasks: [
      'Week 1 Monday: Cook zero-meat protein bowl',
      'Week 2 Monday: Swap standard taco beef for seasoned chickpeas',
      'Week 3 Monday: Enjoy three fully green meals today',
    ],
  },
  'one-green': {
    title: 'One Green Meal Daily',
    desc: 'Consistency is key. Commit to replacing just one standard meal each day with a vibrant, high-protein plant-based alternative.',
    badge: 'Sustained Guard',
    streak: 3,
    color: 'var(--color-purple)',
    tasks: [
      'Commit to a fully plant-based breakfast every day',
      'Prep raw fruits, seed crackers, & hummus as snacks',
      'Try plant-rich options for one week straight',
    ],
  },
  'zero-waste': {
    title: 'Zero Waste Kitchen Week',
    desc: 'Reduce food waste to near zero. Learn to use every vegetable scrap, compost peels, and make creative meals from leftovers.',
    badge: 'Waste Warrior',
    streak: 7,
    color: '#27ae60',
    tasks: [
      'Day 1: Audit your fridge — use the oldest items first',
      'Day 2: Make vegetable broth from scraps (onion skins, carrot tops)',
      'Day 3: Compost all fruit and vegetable peels today',
      'Day 4: Cook a "leftover remix" meal from yesterday\'s extras',
      'Day 5: Plan meals for next 3 days to avoid overbuying',
      'Day 6: Make banana peel chutney or potato skin chips',
      'Day 7: Track and photograph zero waste achieved this week',
    ],
  },
  'protein-power': {
    title: '30-Day Protein Power-Up',
    desc: 'Hit 80g+ plant protein daily for 30 days. Build the habit of intentional protein pairing and discover your favorite combinations.',
    badge: 'Protein Pioneer',
    streak: 30,
    color: '#8e44ad',
    tasks: [
      'Week 1: Track protein intake daily using a simple food diary',
      'Week 2: Try 5 new protein sources you haven\'t eaten before',
      'Week 3: Meal prep high-protein lunches for the entire week',
      'Week 4: Create your own signature high-protein recipe',
      'Bonus: Share your best protein meal with the community',
    ],
  },
  'hydration': {
    title: '21-Day Hydration Habit',
    desc: 'Drink 3L of water daily for 21 days. Transform your energy, skin, digestion, and mental clarity through consistent hydration.',
    badge: 'Water Guardian',
    streak: 21,
    color: '#3498db',
    tasks: [
      'Week 1: Drink 1L before noon every day',
      'Week 2: Replace all sugary drinks with water or herbal tea',
      'Week 3: Track hydration and note changes in energy/skin',
    ],
  },
  'local-seasonal': {
    title: 'Eat Local & Seasonal',
    desc: 'For 14 days, eat only fruits and vegetables that are in season and sourced locally. Discover the flavor difference and environmental benefits.',
    badge: 'Local Hero',
    streak: 14,
    color: '#e67e22',
    tasks: [
      'Day 1-3: Visit a local farmers market and buy seasonal produce',
      'Day 4-7: Cook meals using only seasonal vegetables',
      'Day 8-10: Learn 3 traditional seasonal recipes from your region',
      'Day 11-14: Reduce food miles by sourcing everything within 50km',
    ],
  },
  'mindful-eating': {
    title: '10-Day Mindful Eating',
    desc: 'Slow down. Eat without screens, chew thoroughly, and develop a healthier relationship with food. Notice how plant foods make you feel.',
    badge: 'Mindful Eater',
    streak: 10,
    color: '#1abc9c',
    tasks: [
      'Day 1-2: Eat one meal without any screens or distractions',
      'Day 3-4: Chew each bite 20+ times before swallowing',
      'Day 5-6: Write a food journal entry about how meals make you feel',
      'Day 7-8: Cook a meal from scratch with full attention',
      'Day 9-10: Practice gratitude before each meal',
    ],
  },
  'fitness-fuel': {
    title: 'Vegan Fitness Fuel Challenge',
    desc: 'Combine plant-based nutrition with daily movement for 14 days. Pre and post-workout meals designed for optimal performance.',
    badge: 'Green Athlete',
    streak: 14,
    color: '#e74c3c',
    tasks: [
      'Day 1-3: Prep plant-based pre-workout snacks (banana + PB)',
      'Day 4-7: Post-workout recovery meals with 20g+ plant protein',
      'Day 8-10: Try a new physical activity fueled entirely by plants',
      'Day 11-14: Track performance improvements and energy levels',
    ],
  },
  'community-cook': {
    title: 'Cook for Community',
    desc: 'Share the love of plant-based food by cooking for others. Prepare vegan meals for friends, family, or neighbors for 5 days.',
    badge: 'Community Chef',
    streak: 5,
    color: '#9b59b6',
    tasks: [
      'Day 1: Cook a vegan meal for a non-vegan friend',
      'Day 2: Share a plant-based recipe with a family member',
      'Day 3: Bring vegan snacks to share at work/college',
      'Day 4: Host a small vegan lunch or dinner party',
      'Day 5: Post your cooking experience and inspire others',
    ],
  },
};
